import type {AgentRecommendation,CoolingIntervention,MaintenanceAlert,Neighbourhood,ScenarioResult,SensorReading,Stakeholder} from './types';
export const neighbourhoods:Neighbourhood[]=[
{id:'nw',name:'Neustadt-West',latitude:50.006,longitude:8.252,surfaceTemperature:47.2,airTemperature:36.8,canopyCoverage:9,population:18750,vulnerablePopulationPercentage:31,imperviousSurfacePercentage:84,availableLand:3200,availableRoofArea:12500,waterAvailability:'medium',heatRiskScore:94,vulnerabilityScore:86,priorityScore:91,humidity:42,solarExposure:'Very high',wind:1.8,soilMoisture:18},
{id:'al',name:'Altstadt',latitude:49.999,longitude:8.271,surfaceTemperature:44.8,airTemperature:35.9,canopyCoverage:12,population:16900,vulnerablePopulationPercentage:28,imperviousSurfacePercentage:79,availableLand:2100,availableRoofArea:8900,waterAvailability:'low',heatRiskScore:86,vulnerabilityScore:78,priorityScore:84,humidity:45,solarExposure:'High',wind:2.1,soilMoisture:22},
{id:'mo',name:'Mombach',latitude:50.021,longitude:8.226,surfaceTemperature:42.1,airTemperature:34.7,canopyCoverage:17,population:14150,vulnerablePopulationPercentage:24,imperviousSurfacePercentage:68,availableLand:5800,availableRoofArea:11200,waterAvailability:'high',heatRiskScore:73,vulnerabilityScore:69,priorityScore:71,humidity:48,solarExposure:'High',wind:2.8,soilMoisture:31},
{id:'ob',name:'Oberstadt',latitude:49.984,longitude:8.263,surfaceTemperature:39.4,airTemperature:33.1,canopyCoverage:28,population:22500,vulnerablePopulationPercentage:19,imperviousSurfacePercentage:51,availableLand:7400,availableRoofArea:15200,waterAvailability:'medium',heatRiskScore:55,vulnerabilityScore:52,priorityScore:53,humidity:52,solarExposure:'Moderate',wind:3.2,soilMoisture:38},
{id:'go',name:'Gonsenheim',latitude:50.001,longitude:8.205,surfaceTemperature:36.7,airTemperature:31.8,canopyCoverage:38,population:25300,vulnerablePopulationPercentage:16,imperviousSurfacePercentage:39,availableLand:9200,availableRoofArea:13400,waterAvailability:'high',heatRiskScore:32,vulnerabilityScore:41,priorityScore:35,humidity:55,solarExposure:'Moderate',wind:3.7,soilMoisture:44}];
export const interventions:CoolingIntervention[]=[
{id:'trees',name:'Medium-canopy native trees',cooling:'1.5–3.0°C local',costLevel:'Medium',waterDemand:'Medium',landRequirement:'Street pits',maintenance:'Medium',timeToBenefit:'5–10 years',suitable:'Wide streets, school corridors',limitations:'Underground utilities; establishment watering'},
{id:'park',name:'Pocket parks',cooling:'2.0–4.0°C local',costLevel:'High',waterDemand:'Medium',landRequirement:'400+ m²',maintenance:'High',timeToBenefit:'2–5 years',suitable:'Dense blocks, vacant public land',limitations:'Land competition and ongoing care'},
{id:'roof',name:'Green roofs',cooling:'0.5–2.0°C nearby',costLevel:'High',waterDemand:'Low–medium',landRequirement:'Suitable roofs',maintenance:'Medium',timeToBenefit:'1–2 years',suitable:'Flat municipal roofs',limitations:'Structural load and access'},
{id:'shade',name:'Shaded bus stops',cooling:'Up to 8°C felt',costLevel:'Low',waterDemand:'None',landRequirement:'Minimal',maintenance:'Low',timeToBenefit:'Immediate',suitable:'Transit and care corridors',limitations:'Limited area of influence'},
{id:'rain',name:'Rain gardens & harvesting',cooling:'0.5–1.5°C local',costLevel:'Medium',waterDemand:'Net saving',landRequirement:'Linear/verge',maintenance:'Medium',timeToBenefit:'1–3 years',suitable:'Drainage low points',limitations:'Soil infiltration and contamination'},
{id:'corridor',name:'Natural ventilation corridors',cooling:'1.0–2.5°C district',costLevel:'High',waterDemand:'None',landRequirement:'Planning control',maintenance:'Low',timeToBenefit:'5–15 years',suitable:'Redevelopment districts',limitations:'Long planning horizon'}];
export const agents:AgentRecommendation[]=[
{name:'Heat Monitoring Agent',status:'Analysis complete',inputs:'72 hourly temperature samples · land cover',finding:'Peak exposure 14:00–18:00; 5 persistent hotspots.',confidence:92,action:'Prioritise west-facing streets before Thursday peak.'},
{name:'Vulnerability Assessment Agent',status:'Analysis complete',inputs:'Population profile · 14 public facilities',finding:'2,840 high-risk residents lack nearby cooling.',confidence:88,action:'Focus the school and elderly-care corridor.'},
{name:'Nature-Based Solution Agent',status:'6 options screened',inputs:'Canopy · soil · street width · roofs',finding:'Native trees plus green roofs fit available sites best.',confidence:84,action:'Advance a mixed intervention package.'},
{name:'Resource Optimisation Agent',status:'Constraints balanced',inputs:'€4.2M · 28 ML water · 3.2 ha land',finding:'Portfolio delivers 34% more benefit than equal allocation.',confidence:86,action:'Reserve 12% for establishment maintenance.'},
{name:'Evaluation Agent',status:'Projection ready',inputs:'Intervention evidence ranges · local context',finding:'Expected cooling range is 1.8–2.6°C after maturity.',confidence:79,action:'Validate with shaded/unshaded monitoring pairs.'}];
export const scenarios:ScenarioResult[]=[
{id:'a',name:'Low-cost shade strategy',tag:'Best for budget',color:'#7C5CFC',trees:85,roof:0,park:0,shade:14,cooling:1.2,cost:1.4,water:8,land:0.7,people:12400,energy:5,carbon:38,maintenance:82,equity:78,time:'2–5 years'},
{id:'b',name:'Balanced green infrastructure',tag:'Best overall',color:'#2F9D70',trees:140,roof:4200,park:1200,shade:8,cooling:2.4,cost:3.8,water:19,land:1.8,people:21800,energy:14,carbon:96,maintenance:68,equity:91,time:'3–8 years'},
{id:'c',name:'Maximum cooling strategy',tag:'Best for cooling',color:'#E8703A',trees:260,roof:9200,park:3400,shade:16,cooling:3.6,cost:7.9,water:42,land:3.9,people:29600,energy:27,carbon:184,maintenance:48,equity:84,time:'5–12 years'}];
export const sensors:SensorReading[]=[{name:'Current temperature',value:'34.6°C',status:'Elevated'},{name:'Soil moisture',value:'24%',status:'Attention'},{name:'Humidity',value:'46%',status:'Normal'},{name:'Irrigation',value:'Active',status:'Zone 3'},{name:'Tree health',value:'82 / 100',status:'Good'},{name:'Water consumption',value:'18.4 m³',status:'Today'},{name:'Cooling performance',value:'−1.9°C',status:'On target'},{name:'Maintenance alerts',value:'4',status:'2 urgent'}];
export const alerts:MaintenanceAlert[]=[{title:'Low soil moisture detected',location:'Goethe Street trees',severity:'high',time:'18 min ago'},{title:'Irrigation leakage suspected',location:'Pocket Park 02',severity:'high',time:'1 hr ago'},{title:'Tree stress identified',location:'School corridor',severity:'medium',time:'3 hrs ago'},{title:'Green-roof temperature above threshold',location:'Civic Hall',severity:'medium',time:'5 hrs ago'}];
export const stakeholders:Stakeholder[]=[{group:'System owners',members:['Municipal government','Environmental agencies','Building owners'],icon:'01'},{group:'Direct users',members:['Urban planners','Parks departments','Public-health authorities','Facility managers','Housing authorities'],icon:'02'},{group:'Data providers',members:['Meteorological agencies','Satellite-data providers','IoT sensor providers','Water utilities','Energy utilities'],icon:'03'},{group:'Implementation partners',members:['Landscape architects','Construction companies','Irrigation specialists','AI developers','Universities'],icon:'04'},{group:'Beneficiaries',members:['Residents','Schools','Hospitals','Businesses','Elderly-care centres','Vulnerable communities'],icon:'05'}];
